- name: Add new haproxy root configuration
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  tags: haproxy-config

- name: ensure haproxy is running
  service: name=haproxy state=restarted enabled=yes
  tags: haproxy-config
