- name: update settings for a file store
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    mode: 0600
    backup: yes
  tags: sysctl-config

- name: reload sysctl.conf
  command: /sbin/sysctl -p /etc/sysctl.conf
  tags: sysctl-config
